### ISSUE TITLE
Fluides Design

### ISSUE THREAD

**Issue by johnfidel** [johnfidel/IntTec_MiniProject#3]
Die Seite soll auf Smartphone (IPhone 4)
und Desktop ordentlich aussehen

**Comment by johnfidel** [comment]
Hy Hatus
How does it look like with this features?

**Comment by HatusPeters** [comment]
New note page already in fluid design.
Other pages will follow the same pattern.

**Comment by johnfidel** [comment]
CreateNote and EditNote are working perfectly fluid -> good work!

But All Notes View is not yet working. Can you do that?

**Comment by HatusPeters** [comment]
Ich habe einige Sachen ausprobiert, aber mit <table> kann man kaum etwas machen ohne aufwendige Umstellungen zu machen, wie Bootstrap auf 4.0 zu aktualisieren und Packete importieren. Ich werde die Darstellung in etwas <div> umbauen. Dann soll wieder gehen. Morgen melde ich mich wieder.

**Comment by HatusPeters** [comment]
Layout mit Bootstrap Grid System angepasst.
